version: "3"
services:
 frontend:
   build: ./frontend/
   container_name: frontend
   ports:
     - "8080:8080"
   volumes:
     - ./frontend/app:/app
     - /frontend/app/node_modules
   working_dir: /app
   command: yarn serve